apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: gowt
  ports:
  - name: http
    protocol: TCP
    port: 80 # Port to access service
    targetPort: 8080 # Port in the pod
